# fly.toml app configuration file generated for api-vietnamese-chuviettay-to-text on 2026-06-24T07:14:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-vietnamese-chuviettay-to-text'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '2gb'
  memory_mb = 2048
  processes = ['app']
  size = 'shared-cpu-1x'
